version: "3.5"

services:
  api01: &api
    build: ./
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8008:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  # api02:
  #   <<: *api
  #   hostname: api02
  #   ports:
  #     - "3002:3000"
  
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.15"
  #         memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=112131
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_backend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1